/**
 * @version 1.0.0
 *
 * Snippet Name: RT Form Errors
 * Summary: errors generated by forms
 * Description: verbose description of the error thrown by the form field
 *
 * File Changelog
 *
 * Author                       | Date            | Changes
 * =====================================================================================================================
 * Luca Bertolini               | 26/02/2021      | Initial Import
 */

export const RT_FORM_ERRORS = {

  // MAX = 'Il numero deve essere compreso tra 0 e 100',
  // MIN = 'Il numero deve essere compreso tra 0 e 100',
  // TOTAL = 'La somma dei campi deve essere uguale a 100',
  // REQUIRED = 'Il campo è obbligatorio',
  // INT = 'Il valore deve essere intero',
  // EMAIL = 'Email non valida',
  // STRONG_PSW = 'La password deve essere lunga almeno 8 caratteri e contenere una maiuscola, un numero e un simbolo',
  // MATCH = 'Le due password non corrispondono',
  // BIRTH_DATE = 'Data di nascita non valida',
  // FISCAL_CODE = 'Codice Fiscale non valido',
  // PHONE = 'Telefono non valido',
  // NUM_POSITIVE = 'Il numero deve essere positivo'
}
