export enum COLUMN_TYPE {
  DATE = 'DATE',
  LONG_DATE = 'LONG_DATE',
  NUMBER = 'NUMBER',
  STRING = 'STRING',
  TIME_DATE = 'TIME_DATE',
  BOOLEAN = 'BOOLEAN',
  EDITABLE = 'EDITABLE',
  ICON = 'ICON',
}
