export enum INDEX_CONFIGURATION_KEY {
  TEAM = 'TEAM',
  CUSTOMER = 'CUSTOMER',
  PROJECT = 'PROJECT',
  RELEASE = 'RELEASE',
  TRACKER = 'TRACKER',
  REPORT = 'REPORT',
  DAYOFF = 'DAYOFF',
  HOURSTAG = 'HOURSTAG',
  PROJECT_HOURS = 'PROJECT_HOURS',
  RELEASE_HOURS = 'RELEASE_HOURS',
}
