export enum INDEX_CONFIGURATION_KEY {
  APP_USERS = 'APP_USERS',
  ADMIN_USERS = 'ADMIN_USERS',
  DEADLINES = 'DEADLINES',
  FILES = 'FILES',
  EXPERT_REQUESTS = 'EXPERT_REQUESTS',
  DELETE_REQUESTS = 'DELETE_REQUESTS',
  PARTNER_REQUESTS = 'PARTNER_REQUESTS',
}

